version: '3'
services:
  app:
    container_name: movie-catalog-service
    build: ./movie-catalog-service/
    depends_on:
      - discovery-server
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka"}}}}'
  movie-info-service:
    container_name: movie-info-service
    build: ./movie-info-service/
    depends_on:
      - discovery-server
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka"}}}}'
  ratings-data-service:
    container_name: ratings-data-service
    build: ./ratings-data-service/
    depends_on:
      - discovery-server
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://discovery-server:8761/eureka"}}}}'
  discovery-server:
    container_name: discovery-server
    build: ./discovery-server/
    ports:
      - "8761:8761"